// <auto-generated />
namespace TreinaWeb.Musica.Servicos.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdicaoMusic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicaoMusic));
        
        string IMigrationMetadata.Id
        {
            get { return "201908270138168_AdicaoMusic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
